"""new fields in user model

Revision ID: 42002fe54eb4
Revises: 82fa0d133cbf
Create Date: 2018-04-14 16:49:48.591044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42002fe54eb4'
down_revision = '82fa0d133cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
